### ISSUE TITLE
Weather Screen

### ISSUE THREAD

**Issue by kyleb13** [kyleb13/MobileAppsGroup1#1]
- [x] Must have 3 tabs.
- Appear on:
- [ ] Maintained on the notification bar even the app is off.
- [ ] App is opened
- Display:
- [ ] Location which user choose.
- [x] Temperature right now
- [ ] Real feel
- [x] Weather Condition
- [x] Humidity
- [x] Temperature follows times (24 hours).
- [x] Temperature for next 3 days.
- Task bar:
- [ ]  Location: open location layout where user can choose location and save it.
   - [ ] Map: display location where user's device or chosen location.
   - [ ] The roll bar and auto fill when user type in any location, zip code.
   - [ ] The button save so the map can save the coordinates of location user chose.
- Nice to have:
- [ ] Display different background depends on time or weather.

**Comment by sam2b** [comment]
@tambui142 , here is a free Weather API: https://openweathermap.org/appid
Just follow the steps to get set up.

** Here is an example of the JSON that is returned: **
http://samples.openweathermap.org/data/2.5/forecast?id=524901&appid=b1b15e88fa797225412429c1c50c122a1

**Comment by sam2b** [comment]
Tam Finished.
