### ISSUE TITLE
Weather Connection

### ISSUE THREAD

**Issue by tambui142** [kyleb13/MobileAppsGroup1#42]
I have acquired an API key for OpenWeather.org.
ffcc151bc33bd88d59414e3373ee8858

Endpoint URL for the forecast in Tacoma, WA:
http://api.openweathermap.org/data/2.5/forecast?id=5812944&appid=ffcc151bc33bd88d59414e3373ee8858

For examples on how to use Java to parse this JSON data, see account.js and AccountSettingsFragment.java

**Comment by sam2b** [comment]
Done in PR #82
